### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by AudricSan** [FUE5BASE/FUE5-Exporter#2]
I get this error some times when i'll try to export my factory

"The mod FUE5 Exporter (1.0.0) has generated an unrecoverable error.
Please inform the author of this error.

Error while running event FUE5Exporter::on_player_selected_area (ID 51)
__FUE5Exporter__/scripts/wire_connections.lua:46: attempt to index field '?' (a nil value)
stack traceback:
	__FUE5Exporter__/scripts/wire_connections.lua:46: in function 'get_wire_connections'
	__FUE5Exporter__/control.lua:33: in function 'process'
	__FUE5Exporter__/control.lua:65: in function <__FUE5Exporter__/control.lua:64>"

**Comment by Atria1234** [comment]
Do you have some modded buildings? Power poles to be specific

**Comment by AudricSan** [comment]
Oh yes, indeed I didn't think about it anymore but I do have a mod to make Power poles with lights.

**Comment by Atria1234** [comment]
Anyway it will be fixed in next version so it doesn't export anything but also doesn't crash
